
gamma = 2*pi*42.58e6;

iv = ImagingVolume([-1 1], 0, 1e99, 1e99, 1, ...
                   'M', [sqrt(2/3) sqrt(2/3); ...
                    0 0; 1/sqrt(3) -1/sqrt(3)], ...
                   'Annotation', {'Parallel', 'Antiparallel'});

[S,t] = seemri(iv, 1, [], [], [], ADC(1e-6, 1e-9), ...
               'Frame', 'Stationary');
